apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ca7b2r3rj-nodejs
  janus-idp.io/tekton: ca7b2r3rj-nodejs
  backstage.io/kubernetes-id: ca7b2r3rj-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ca7b2r3rj-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
