apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ca7b2r3rj-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ca7b2r3rj-nodejs 
  name: ca7b2r3rj-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: ca7b2r3rj-nodejs 
